// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzP8UNB-2VzvcLgzCRcWcla9mG-z2cPGE',
    appId: '1:37898313383:web:ce1eff7136567a029e4582',
    messagingSenderId: '37898313383',
    projectId: 'seat-allocation-3dffa',
    authDomain: 'seat-allocation-3dffa.firebaseapp.com',
    storageBucket: 'seat-allocation-3dffa.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbptAe4sQbr2fCnrGcqpE8Na4-ufDHPS8',
    appId: '1:37898313383:android:04ad75b0de74033b9e4582',
    messagingSenderId: '37898313383',
    projectId: 'seat-allocation-3dffa',
    storageBucket: 'seat-allocation-3dffa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBE1FQTwbX4gpOv0QXgrRafP9POMhX5d-o',
    appId: '1:37898313383:ios:d57db439d43b8fec9e4582',
    messagingSenderId: '37898313383',
    projectId: 'seat-allocation-3dffa',
    storageBucket: 'seat-allocation-3dffa.appspot.com',
    iosBundleId: 'com.example.seatAllocation',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBE1FQTwbX4gpOv0QXgrRafP9POMhX5d-o',
    appId: '1:37898313383:ios:de02494e2204ce6d9e4582',
    messagingSenderId: '37898313383',
    projectId: 'seat-allocation-3dffa',
    storageBucket: 'seat-allocation-3dffa.appspot.com',
    iosBundleId: 'com.example.seatAllocation.RunnerTests',
  );
}
